---
apiVersion: v1
kind: Service
metadata:
  namespace: vpn
  name: ipsec-vpn-server-aws-nlb
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path:   /metrics
        prometheus.io/port:   '9100'
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=dev,owner=SRE,job=ipsec-vpn-server"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb 
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "6"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "20"
        service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
        service.kubernetes.io/local-svc-only-bind-node-with-pod: "true"
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
  labels:
    app: ipsec-vpn-server
spec:
  type: LoadBalancer
  ports:
  - name: vpnisakmp
    port: 500
    targetPort: 500
    protocol: UDP
  - name: vpnike
    port: 4500
    targetPort: 4500
    protocol: UDP
  - name: port1701  
    port: 1701
    targetPort: 1701
    protocol: UDP    
  selector:
    app: ipsec-vpn-server
